config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cities, only: [:show, :index] do
    resources :reviews, only: [:create, :update, :destroy]
    resources :wishlists, only: [:create, :destroy]
    get '/cost-of-living-estimator', to: 'pages#estimator', as: 'estimator'
    post 'send_city_email', to: 'cities#send_details'
    post 'send_city_offers_email', to: 'cities#send_offers'
  end

  resources :wishlists, only: [:index]

  get 'my_profile', to: 'pages#my_profile', as: 'my_profile'

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :reviews, dependent: :destroy
  has_many :wishlists
  has_many :users, through: :wishlists
  validates :name, presence: true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  has_many :reviews, through: :cities
  validates :name, :language, :currency, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :city
  belongs_to :user
  validates :content, presence: true, length: { minimum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :wishlists, dependent: :destroy
  has_many :cities, through: :wishlists
  has_one_attached :photo
  after_create :send_welcome_email

  def wishlists?(city)
    city.wishlists.where(user_id: id).any?
  end

  def profile_picture
    photo.attached? ? photo : 'digital-nomad.png'
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :city
  belongs_to :user
  validates :city, uniqueness: { scope: :user, message: "Wishlists must be unique for city/user scope" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username preferences photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find_by(name: 'general')
    authorize @chatroom
    @message = Message.new
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      sql_query = " \
        cities.name @@ :query \
        OR countries.name @@ :query \
      "
      @cities = policy_scope(City).joins(:country).where(sql_query, query: "%#{params[:query]}%")
    else
      @cities = policy_scope(City)
    end
  end

  def show
    @city = City.find(params[:id])
    @review = Review.new # So we can render the review form here
    authorize(@city)
    respond_to do |format|
      format.html
      format.json { render json: @city }
    end
  end

  def send_details
    @city = City.find(params[:city_id])
    authorize(@city)
    CityMailer.city_details(current_user, @city).deliver_now
  end

  def send_offers
    @city = City.find(params[:city_id])
    @prices = params[:prices]
    authorize(@city)
    CityMailer.city_offers(current_user, @city, @prices).deliver_now
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    authorize @message
    if @message.save
      respond_to do |format|
        format.js do
          ChatroomChannel.broadcast_to(
            @chatroom,
            render_to_string(partial: "message", locals: { message: @message })
          )
          render "create.js.erb"
        end
      end
    else
      render "chatrooms/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @cities = City.all

    @markers = @cities.map do |city|
      {
        lat: city.latitude,
        lng: city.longitude,
        info_window: render_to_string(partial: "cities/info_window", locals: { city: city }),
        city_type: city.city_type
      }
    end
  end

  def my_profile
  end

  def estimator
    @cities = City.all
    @city = City.find(params[:city_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @city = City.find(params[:city_id])
    @review = Review.new(review_params)
    @review.city = @city
    @review.user = current_user
    authorize(@review)
    if @review.save
      redirect_to city_path(@city, anchor: "review-#{@review.id}")
    else
      render template: 'cities/show'
    end
  end

  def update
    @review = Review.find(params[:id])
    @review.update(params[:content])
  end

  def destroy
    @review = Review.find(params[:id])
    authorize(@review)
    @review.destroy
    redirect_to city_path(@review.city)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_city, only: %i[create destroy]

  def index
    skip_policy_scope
    @wishlists = User.includes(:wishlists).find(current_user.id)
  end

  def create
    @wishlist = Wishlist.where(user: current_user, city: @city).first_or_create
    authorize(@wishlist)
    raise unless @wishlist.save

    respond_to do |format|
      format.js
      format.html { redirect_to @city }
    end
  end

  def destroy
    @wishlist = Wishlist.where(city: @city, user: current_user)
    authorize(@wishlist)
    @wishlist.destroy_all
    respond_to do |format|
      format.js
      format.html { redirect_to root }
    end
  end

  private

  def set_city
    @city = City.find(params[:city_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/temp_helper.rb
module TempHelper
  def temp_average(city, season)
    arr = city.weather['temp']
    mid_year = (arr[5, 3].sum / 3).round(1)
    end_year = ((arr[0, 2].sum + arr[-2]) / 3).round(1)
    if city.latitude >= 0 && season == 'summer'
      mid_year
    elsif city.latitude >= 0 || season == 'summer'
      end_year
    else
      mid_year
    end
  end
end

app/views/chatrooms/show.html.erb
<div class="adjust" style="height:100px"></div>
<div class="container my-4">
  <%= link_to 'Back', :back, class:"btn-flat" %>
  <h1 style="text-align: center; font-size: 30px; font-weight: bold; color: #c57b57;">Nomad Chat</h1>
  <div id="messages" data-chatroom-id="<%= @chatroom.id %>" class="p-4 my-3" style="background-color: #F4F4F4; border-radius: 25px;">
    <%= render partial: "messages/message", collection: @chatroom.messages.includes(:user), cached: true %>
  </div>
  <%= simple_form_for [ @chatroom, @message ], remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}" %>
  <% end %>
</div>

app/views/cities/_city_info.html.erb
<div class="card pl-3 pt-3 collapse show" id="collapseInfo" data-parent="#menu">
  <h5 class="card-title font-weight-bold border-bottom pb-2">Global informations:</h5>
  <p><strong>☀️ Median yearly temperature: </strong> <%=  city.weather['temp'][-1] %>º C</p>
  <p><strong>📢 Language: </strong> <%=  city.country.language %></p>
  <p><strong>💵 Currency: </strong> <%=  city.country.currency %></p>
</div>

app/views/cities/_costs_card.html.erb
<div class="mt-5 mb-4">
  <div class="card my-4 d-flex align-items-center justify-content-center" style="height: 150px; width: 27rem; background-color: #006d77; color: white;">
    <div class="row card-body d-flex align-items-center justify-content-center">
      <h5 class="card-title font-weight-bold pb-2">Cost of Living Estimator</h5>
      <p class="card-text d-flex justify-content-center" style="width: 182px;">
        <%= link_to "$$$$$", city_estimator_path(city), class:"btn-round-sm glowing"%>
      </p>
    </div>
  </div>
</div>

app/views/cities/_form.html.erb
<%= simple_form_for([ @city, @review ], remote: true, html: {class:"form-label"}) do |f| %>
  <%= f.input :content, label: 'Leave a review 🌟', as: :text, input_html: {class:"form-review"}, style:"border-radius: 40px;" %>
  <%= f.button :submit, class:"btn-round", value: 'Add review' %>
<% end %>

app/views/cities/_heart_wishlist.html.erb
<% city ||= @city %>
<div id="heart-<%= city.id %>">
<% if user_signed_in? && current_user.wishlists?(city) %>
  <%= link_to destroy_wishlist_path({city_id: city}), method: :delete, class:"card-category" do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to new_user_session_path, class:"card-category" do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
</div>

app/views/cities/_info_window.html.erb
<div class="mapboxgl-popup">
  <div class = "mapboxgl-popup-content">
    <h5><strong><%= link_to city.name, city_path(city) %> </strong></h5>
    <p>
      ☀️ Median summer temperature: <%= temp_average(city, 'summer') %> °C
      <br> ❄️ Median winter temperature: <%= temp_average(city, 'winter') %> °C
      <br><br><strong> Overall Score: <%= city.overall_score %> </strong>
    </p>
  </div>
</div>

app/views/cities/_reviews.html.erb
<div class="review border-top pt-5 pb-5">
  <div class="review  mb-5" style="color: #c57b57; font-family: 'Nothing You Could Do', cursive;">
    <div class="review-title font-weight-bold text-uppercase">
      <h4><strong>...Reviews from Nomads</strong></h4>
    </div>
    <p>Find out opinion from nomads who already went to this city </p>
  </div>
  <div class="row">
    <div class="col-6">
      <%= render city.reviews.includes([:user]), cached: true || "Nobody has reviewed #{city.name} yet, have you visited it? Leave a review for others!" %>
    </div>
    <div class="col-6">
      <% if user_signed_in? %>
        <%= render partial: "cities/form" %>
      <% else %>
        <%= button_to "Login to wishlist cities and much more!", new_user_session_path, class:"btn-flat" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cities/_score.html.erb
<div class="card pl-3 pt-3 collapse" id="collapseScore" data-parent="#menu">
  <h3 class="pb-2 border-bottom">Overall Score: <div class="stars" style="--rating: <%= @city.overall_score %>;"></div></h3>
  <div class="row py-2">
    <div class="col-6">
      <h5>👌 Safety: <div class="stars" style="--rating: <%= @city.score["safety"] %>;"></div></h5>
      <h5>📡 Internet: <div class="stars" style="--rating: <%= @city.score["internet"] %>;"></div></h5>
      <h5>😝 Fun: <div class="stars" style="--rating: <%= @city.score["fun"] %>;"></div></h5>
    </div>
    <div class="col-6">
      <h5>💨 Air quality: <div class="stars" style="--rating: <%= @city.score["air"] %>;"></div></h5>
      <h5>🎓 English speaking: <div class="stars" style="--rating: <%= @city.score["english"] %>;"></div></h5>
    </div>
  </div>
</div>

app/views/cities/_send_info.html.erb
<div class="mt-5 mb-4">
  <div class="card my-4 d-flex align-items-center justify-content-center" style="height: 150px; width: 27rem; background-color: #006d77; color: white;">
    <div class="row card-body d-flex align-items-center justify-content-center">
      <h5 class="card-title font-weight-bold pb-2">Don't want to miss anything?</h5>
      <p class="card-text">
        <script></script>
        <%= link_to 'Send me this info!', city_send_city_email_path(city), method: :post,  class:"btn-round-sm" %>
      </p>
    </div>
  </div>
</div>

app/views/cities/_send_offer.html.erb
<div class="d-flex justify-content-center">
  <div class="card my-4 text-center" style="width: 18rem; background-color: #006d77; color: white;">
    <div class="card-body">
      <h5 class="card-title font-weight-bold pb-2">Don't want to miss anything?</h5>
      <p class="card-text">
        <%= form_with url: city_send_city_offers_email_path(city) do |form| %>
          <%= form.hidden_field :prices %>
          <%= form.submit "Send me this info!", class:"btn btn-round-full" %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/cities/_show_menu.html.erb
<div>
  <button class="btn btn-show-menu" type="button" data-toggle="collapse" data-target="#collapseInfo" aria-expanded="false" aria-controls="collapseExample">
    City Info
  </button>
  <button class="btn btn-show-menu collapsed" type="button" data-toggle="collapse" data-target="#collapseWeather" aria-expanded="false" aria-controls="collapseExample">
    Weather
  </button>
  <button class="btn btn-show-menu collapsed" type="button" data-toggle="collapse" data-target="#collapseScore" aria-expanded="false" aria-controls="collapseExample">
    Score
  </button>
</div>

app/views/cities/_weather.html.erb
<div class="card pl-3 pt-3 collapse" id="collapseWeather" data-parent="#menu">

  <h3>Here's the historical weather data for <%= city.name %></h3>
  <p>Daily mean temperature by month, in celsius</p>
  <ul class="list-group list-group-horizontal city-historic-temp">
    <% city.weather['temp'].each do |month| %>
      <li class="list-group-item"><%= month %></li>
    <% end %>
  </ul>

  <p>Average rainfall by month, in mm </p>
    <ul class="list-group list-group-horizontal city-historic-temp">
    <% city.weather['rain'].each do |month| %>
      <li class="list-group-item"><%= month %></li>
    <% end %>
  </ul>

  <p>Mean monthly sunshine hours</p>
    <ul class="list-group list-group-horizontal city-historic-temp">
    <% city.weather['sunshine'].each do |month| %>
      <li class="list-group-item"><%= month %></li>
    <% end %>
  </ul>
</div>

app/views/cities/_wishlists.html.erb
<div id="wishlist-<%= @city.id %>">
<% if user_signed_in? && current_user.wishlists?(@city) %>
  <%= button_to "Remove from wishlist", city_wishlist_path(@city, current_user), method: :delete, class:"btn-flat", remote: true %>
<% elsif user_signed_in? %>
  <%= button_to "Add to wishlist", city_wishlists_path(@city), class:"btn-flat", remote: true %>
<% else %>
  <%= button_to "Login to wishlist cities and much more!", new_user_session_path, class:"btn-flat btn-primary" %>
<% end %>
</div>

app/views/cities/index.html.erb
<div class="adjust" style="height:100px"></div>

<div class="container mt-4 mb-5">
  <br>
  <h1 style="text-align: center; font-size: 30px; font-weight: bold; color: #c57b57; padding-bottom: 25px;">Best Nomad Hubs</h1>
  <div class="question pb-3 bold" style="text-align: center; font-size: 24px; font-weight: bold; color: #006d77; font-family: 'Nothing You Could Do', cursive;">
    Where is your next stop?
  </div>
  <%= simple_form_for :search, url: cities_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
       params[:query],
       class: "form-control",
       placeholder: "go global"%>
      <%= submit_tag "", class: "btn btn-search" %>
        <i class="fas fa-search" style="padding-top: 5px; padding-right: 6px; font-size: 20px;"></i>
    </div>
  <% end %>
</div>
<div class="container my-4">
  <div class="cards">
    <%= render partial: "shared/city", collection: @cities %>
  </div>
</div>

app/views/cities/show.html.erb
<% filename = "cities/#{@city.name.downcase.split[0]}.jpg" %>
<div class="banner-city text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path filename, crop: :fill%>');">
  <div class="container text-center link navbar-trigger" style="color:white;">
    <div class="place pb-3">
      <h1><strong><%=@city.name%> </strong></h1>
      <h5><strong><%=@city.country.name%></strong></h5>
    </div>
    <div id="wishlists">
      <%= render partial: "cities/wishlists" %>
    </div>
  </div>
</div>

<div class="container my-5">
  <div class="content mb-5" id="menu">
    <%= render partial: "cities/show_menu" %>
    <%= render partial: "cities/city_info", locals: { city: @city } %>
    <%= render partial: "cities/weather", locals: { city: @city } %>
    <%= render partial: "cities/score", locals: { city: @city } %>
    <div class="row d-flex justify-content-around">
      <%= render partial: "cities/costs_card", locals: { city: @city } %>
      <%= render partial: "cities/send_info", locals: { city: @city } %>
    </div>
    <%= render partial: "cities/reviews", locals: { city: @city } %>
  </div>
  <%= link_to 'Back', cities_path, class:"btn-flat" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NomadWorker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.3.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.3.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <div id="page-container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <div id="content-wrap">
        <%= yield %>
        <%= render 'shared/chat' if user_signed_in? %>
      </div>
      <%= render 'shared/footer', cached: true %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message-container border-bottom mt-3" id="message-<%= message.id %>" >
  <i class="author">
    <span class="mr-3 ml-1" ><%= message.user.username %></span>
    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
  </i>
  <p class="ml-2"><%= message.content %></p>
</div>

app/views/messages/create.js.erb
document.querySelector("#messages").scrollTo(0,document.querySelector("#messages").scrollHeight);

app/views/pages/_budgets.html.erb
<div class="py-5 border-bottom">
  <div class="d-flex justify-content-center" style="color: #495867; font-weight: bold;">
    <h4>What's your preference?</h4>
  </div>
  <div class="row d-flex justify-content-around mt-4">
    <div class="common-search">
      <a href="" class="btn btn-round-full" id="economical-search">On a budget</a>
    </div>
    <div class="common-search">
      <a href="" class="btn btn-round-full" id="expensive-search">Living large</a>
    </div>
  </div>
</div>

app/views/pages/_carousel.html.erb
<div id="wrap" class="d-flex">
  <a href="#" class="hb">
    <div class="c" style="width: 250px">
      <%= image_tag("cities/sydney.jpg", width: 400, height: 400, crop: :fill)%>
      <div class="txt">
        <h1>Sydney</h1>
      </div>
    </div>
  </a>
  <a href="#" class="hb">
    <div class="c" style="width: 350px">
      <%= image_tag("cities/singapore.jpg",  width: 400, height: 400, crop: :fill)%>
      <div class="txt">
        <h1>Singapore</h1>
      </div>
    </div>
  </a>
  <a href="#" class="hb">
    <div class="c" style="width: 300px">
      <%= image_tag("cities/bali.jpg",  width: 400, height: 400, crop: :fill)%>
      <div class="txt">
        <h1>Bali</h1>
      </div>
    </div>
  </a>
  <a href="#" class="hb">
    <div class="c" style="width: 270px">
      <%= image_tag("cities/rome.jpg",  width: 400, height: 400, crop: :fill)%>
      <div class="txt">
        <h1>Rome</h1>
      </div>
    </div>
  </a>
</div>

app/views/pages/_cities_select.html.erb
<div class="py-5 border-bottom">
  <div class="d-flex justify-content-center" style="color: #495867; font-weight: bold;">
    <h4 id="h4-comparator">Compare with another city:</h4>
  </div>
  <div id="toggle-comparator" class="d-flex justify-content-center">
    <select id="comparator">
      <optgroup label="Compare with: ">
        <option value="none">none</option>
        <% cities.each do |city| %>
          <option value="<%= city.id %>"><%= city.name %></option>
        <% end %>
      </optgroup>
    </select>
  </div>
</div>

app/views/pages/_costs_select.html.erb
<div id="data" data-city="<%= city.to_json %>" class="row justify-content-between pr-5">
  <% city.data.each do |category, values| %>
  <div class="col-1">
    <label for="pet-select"><%= category.capitalize %>:</label>
    <select class="selects">
      <optgroup label="<%= category %>">
        <% values.each do |subcategory, _value| %>
          <% if subcategory.split('_')[1] %>
            <option value="<%= subcategory %>"><%= subcategory.split('_')[0].capitalize + ' ' +  subcategory.split('_')[1] %></option>
          <% else %>
            <option value="<%= subcategory %>"><%= subcategory.capitalize %></option>
          <% end %>
        <% end %>
      </optgroup>
    </select>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner d-flex flex-column justify-content-center align-items-center navbar-trigger">
  <video autoplay muted loop id="myVideo">
  <source src="<%= image_path 'hero.mp4' %>" type="video/mp4">
</video>
  <div class = "content align-items-center justify-content-center " id = 'banner-content'>
      <br>
      <br>
      <h1><strong> 🌏 Work from</strong> anywhere in <strong>the world</strong></h1>
      <p> get accurate cost of living data to know where to go next 💻 </p>
    <div class=" col-12 m-0 " >
      <%= link_to "Go nomad ✈️ ", cities_path, class:'btn btn-round btn-flat-home' %>
    </div>
  </div>
</div>
<br>
<div class = 'row adjust'></div>
<%= render partial: 'pages/carousel', cached: true %>
<div class="row justify-content-center pb-4" style="color: black;">
  <%= link_to "Explore nomad hubs", cities_path, class:'btn-round' %>
</div>

<div id="map" class="my-5 ml-auto mr-auto"
    style="width: 75vw; height: 500px; border-top: 1px solid #efe6dd;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<%= render partial: 'pages/features_cards', cached: true %>
<%= render partial: 'pages/socialproof', cached: true %>

<div class="row justify-content-center pb-4" style="color: black;">
  <%= link_to "Nomadize now", cities_path, class:'btn-round' %>
</div>

app/views/reviews/_review.html.erb
<p id="review-<%= review.id %>"> <div class="card-review pl-3 py-3"><p><%= review.user.username %> says: </p> <%= review.content %></div>

</p>
<% if review.user == current_user %>
  <%= link_to 'Delete', city_review_path(@city, review), method: :delete, data: { confirm: 'Are you sure?' },
  class:"btn-flat", remote: true %>
<% end %>

app/views/shared/_city.html.erb
<div class="card-container">
  <%= render partial: "shared/heart", locals: { city: city } %>
  <%= link_to city_path(city) do %>
  <% filename = "cities/#{city.name.downcase.split[0]}.jpg" %>
  <div id="city-<%=city.id%>" class="card-category" style="background-image: url('<%= image_path filename, crop: :fill%>')">
    <span class="link">
      <%= city.name %>
    </span>
  </div>
  <% end %>
</div>

app/views/shared/_heart.html.erb
<% city ||= @city %>
<div id="heart-<%= city.id %>">
<% if user_signed_in? && current_user.wishlists?(city) %>
  <%= link_to city_wishlist_path(city, current_user), method: :delete, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% elsif user_signed_in? %>
  <%= link_to city_wishlists_path(city), method: :post, remote: true do %>
    <i class="far fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to new_user_session_path do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="site-name"> <%= image_tag "logo.png", style: "height: 70px; width: auto;" %> </div>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Explore", cities_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Wishlist", wishlists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Chat", chatroom_path(1), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag current_user.profile_picture, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", my_profile_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/wishlists/create.js.erb
$("#heart-<%= params[:city_id] %>").html("<%= escape_javascript(render('shared/heart')) %>");
$("#wishlist-<%= params[:city_id] %>").html("<%= escape_javascript(render('cities/wishlists')) %>");